import Head from 'next/head'
import SampleTable from '@/components/sampleTable'

export default function Home() {
  return (
    <>
      <Head>
        <title>Column resizer demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <SampleTable />
      </main>
    </>
  )
}
